apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-green
spec:
  selector:
    matchLabels:
      type: example_code
      color: green
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 10%
  template:
    metadata:
      labels:
        type: example_code
        color: green
    spec:
      containers:
      - name: echocolor
        image: reselbob/echocolor:v0.1
        ports:
        - containerPort: 3000
        env:
        - name: COLOR_ECHO_COLOR
          value: GREEN
        - name: COLOR_ECHO_VERSION
          value: V1
